name: tests connect
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**"
  push:
    branches:
      - "develop"
    paths:
      - "**"

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/_sdks_jest.yml
    with:
      workdir: ./lib
